### ISSUE TITLE
Configure the CI Tools and Helper Tools.

### ISSUE THREAD

**Issue by SchoolGuy** [cobbler/libcobblersignatures#13]
Currently PRs are failing sometimes, even when they are good. This is due to the reason that the CI providers are not correctly configured.

To close this issue we have the following AC:

- [ ] Take a look at the Codacy Linters and decide which we will use.
- [ ] Configure choosen Codacy Linters
- [ ] Configure Pyup via a configuration file

**Comment by nodeg** [comment]
Codacy itself has a blog post about 1. https://blog.codacy.com/which-python-static-analysis-tools-should-i-use/

**Comment by SchoolGuy** [comment]
@nodeg Do it. I would love to be consistent there. On the Cobbler side there are some problems but here I think this will be much easier!

**Comment by nodeg** [comment]
Did you wonder what linter this project should use? For consistency reasons I would recommend `pylint` since Cobbler uses it, too.

**Comment by SchoolGuy** [comment]
@nodeg Feel free to peek at Cobbler. It has configured more then `pylint` but I think for now that is indeed enough for me to see this as closed! (Of course we first need the PR to that... XD )

**Comment by SchoolGuy** [comment]
GH does not recognize "partly"

**Comment by nodeg** [comment]
I thought so. So now the only thing missing is`pyup`. How do we proceed here? When I look at the [Cobbler file](https://github.com/cobbler/cobbler/blob/master/.pyup.yml) we could basically copy it over. What do you think?

**Comment by SchoolGuy** [comment]
@nodeg I think this is the best until we have a better solution. I would love to use the bot for fixed deps but sadly that is not yet possible...
