### ISSUE TITLE
GitHub Action to verify signatures.json is correct.

### ISSUE THREAD

**Issue by SchoolGuy** [cobbler/libcobblersignatures#54]
When opening PRs at both the website (https://github.com/cobbler/cobbler.github.io) and the server repo it is at the moment not possible to verify if the JSON is handed in the correct format. It would be nice if we (and others) can verify this with a GitHub Action.

This is dependant on #39.

**Comment by tiltingpenguin** [comment]
Closed with https://github.com/cobbler/libcobblersignatures/pull/55
