### ISSUE TITLE
Unify distro_signatures.json

### ISSUE THREAD

**Issue by tiltingpenguin** [cobbler/libcobblersignatures#57]
Currently we have 3 instances for distro_signatures.json:

1 in libcobblersignatures, 
1 in cobbler and 
1 in cobbler.github.io

We want to unify these and thus reduce the effort for maintaining an example signatures file. The idea is to have a static site in cobbler.github.io that serves the examples for all the different schema versions

**Comment by SchoolGuy** [comment]
I want to extend on this a littlebit more:

- This repository will use GitHub pages to upload all versions of the schema that are available.
- The server repository version of `distro_signatures.json` will be deleted once #44 is done.
- The versions on `cobbler.github.io` will stay unmaintained there for archival purposes.
- The server will use the new schema-based versioning as an URL for updating the `distro_signatures.json` file.
- The new URL should then subsequently look roughly like the following:
  - `https://cobbler.github.io/libcobblersignatures/v1/data.json`
  - `https://cobbler.github.io/libcobblersignatures/v1/schema.json`
- Thus in the repository will at all times live all schemas with all `distro_signatures.json` files in the `main` branch.
- The new repository structure *could* look like the following:
```
...
distro_signatures/
    v1/
        data.json
        schema.json
...
```

**Comment by SchoolGuy** [comment]
This issue is dependant on #63
