### ISSUE TITLE
Switch coverage to codacy

### ISSUE THREAD

**Issue by tiltingpenguin** [cobbler/libcobblersignatures#60]
In order to keep our workflows as similar as possible to cobbler we are switching our code-coverage tool to codacy

The related issue in cobbler: https://github.com/cobbler/cobbler/issues/3365

**Comment by SchoolGuy** [comment]
@tiltingpenguin do you have access to the Codacy repo of libcobblersignatures? If not I would add you in the evening.

**Comment by tiltingpenguin** [comment]
Yes, please do that

**Comment by SchoolGuy** [comment]
Invite sent. Please login via GitHub.
